development:
  adapter: postgresql
  database: uottawasesa
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: uottawasesa
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: uottawasesa
  username: postgres
  password: postgres
  host: localhost
  port: 5432